@startuml
class ChangePasswordViewModel {
    + UserId : long <<get>> <<set>>
    + OldPassword : string <<get>> <<set>>
    + NewPassword : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
}
@enduml
