@startuml
class ChartController {
    + ChartController(chartService:IChartService)
    + <<async>> viewAll(searchModel:ChartSearchModel) : Task<GenericResult<IList<ChartViewModel>>>
    + <<async>> GetDetails(id:int) : Task<ChartViewModel>
}
ControllerBase <|-- ChartController
@enduml
