@startuml
class YearController {
    + YearController(YearService:IYearService)
    + SearchLookup(searchModel:YearLookupSearchModel) : GenericResult<IList<YearLookupViewModel>>
}
ControllerBase <|-- YearController
@enduml
