@startuml
class Startup {
    + Startup(configuration:IConfiguration)
    + ConfigureServices(services:IServiceCollection) : void
    + Configure(app:IApplicationBuilder, env:IWebHostEnvironment, logger:ILoggerService, serviceProvider:IServiceProvider) : void
}
Startup --> "Configuration" IConfiguration
@enduml
